### PR TITLE
Add request scoped AirlineContext (probably needs revision)

### PR DESCRIPTION
**Pull request by aluanhaddad**
Add request scoped AirlineContext

### CODE REVIEW

**Review by MurtuzaTravadi — COMMENTED** [review]
AddScoped for AirlineContext

**Comment by MurtuzaTravadi** [comment]
Thank you for participants @aluanhaddad

**Comment by MurtuzaTravadi** [comment]
@aluanhaddad  you have any idea how can i implement `UnitOfWork` Concept in this Code I have tried but Still getting me same Exception as we discussed in `stackoverflow`

**Comment by aluanhaddad** [comment]
Where does `AirlineContext` come from? I don't see any such class.

**Comment by MurtuzaTravadi** [comment]
@aluanhaddad  you can find `UniversityContext` in (https://github.com/MurtuzaTravadi/DotNetCoreRepositoryPattern/blob/master/DotNetCoreRepositoryPattern.Models/Infrastructure/Data/UniversityContext.cs)

**Pull request merged**
